"""add index and unit to supply_target

Revision ID: 040878089af6
Revises: a2e3300f253c
Create Date: 2026-07-24 17:33:15.028789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '040878089af6'
down_revision = 'a2e3300f253c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supply_target', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column('index', sa.Integer(), nullable=False, server_default='0')
        )

    # ### end Alembic commands ###

    # Backfill existing rows with distinct order values based on id.
    op.execute('UPDATE supply_target SET "index" = id * 1000')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supply_target', schema=None) as batch_op:
        batch_op.drop_column('unit')
        batch_op.drop_column('index')

    # ### end Alembic commands ###
