"""add meeting_point to trip

Revision ID: a2e3300f253c
Revises: 9c62ffdb6669
Create Date: 2026-07-18 13:55:44.162761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2e3300f253c'
down_revision = '9c62ffdb6669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_point', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_column('meeting_point')

    # ### end Alembic commands ###
